export interface Product {
  id: number
  name: string
  sku: string
  brand: string
  category: string
  subcategory: string
  model: string
  price: number
  priceDisplay: string
  priceUnit: string
  moq?: number
  leadTime?: string
  stock: number
  stockLabel: string
  img: string
  images: string[]
  shortDesc: string
  description: string
  spec: string
  specs: { label: string; value: string }[]
  applications: string[]
  tags: string[]
  featured: boolean
  certifications: string[]
}

export const CATEGORIES = [
  'Electrical Equipment',
  'Industrial Machinery',
  'Power & Energy',
  'Tools & Equipment',
  'Safety & Fire Protection',
  'Cables & Accessories',
]

export const CATEGORY_SUBS: Record<string, string[]> = {
  'Electrical Equipment': ['Transformers', 'Switchgear & Circuit Breakers', 'Control Panels & MCC', 'Motors & Drives', 'Metering & Instrumentation'],
  'Industrial Machinery': ['Compressors', 'Pumps & Valves', 'Conveyors & Material Handling', 'Processing Equipment', 'Industrial Fans & Blowers'],
  'Power & Energy': ['Diesel Generators', 'Solar & Renewable', 'UPS & Battery Systems', 'Power Distribution Units', 'Energy Storage'],
  'Tools & Equipment': ['Power Tools', 'Hand Tools', 'Measuring & Testing', 'Lifting & Rigging', 'Pneumatic Tools'],
  'Safety & Fire Protection': ['Personal Protective Equipment', 'Fire Detection & Alarms', 'Fire Suppression Systems', 'Emergency Equipment', 'Safety Signage'],
  'Cables & Accessories': ['Power Cables', 'Control Cables', 'Cable Management', 'Conduits & Fittings', 'Connectors & Terminals'],
}

export const BRANDS = [
  'Siemens', 'ABB', 'Schneider Electric', 'Eaton', 'Legrand',
  'Mitsubishi Electric', 'Bosch', 'Fluke', 'Hilti', '3M',
  'Honeywell', 'Parker',
]

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'High-Voltage Power Transformer',
    sku: 'EE-TRF-001',
    brand: 'Siemens',
    category: 'Electrical Equipment',
    subcategory: 'Transformers',
    model: 'SIDAC 11/0.4kV',
    price: 28500,
    priceDisplay: '$28,500',
    priceUnit: 'per unit',
    moq: 1,
    leadTime: '8–12 weeks',
    stock: 3,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1509390484649-e8f3d1bb0b6d?w=600&h=400&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1509390484649-e8f3d1bb0b6d?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1509390221805-d1c887a72a00?w=800&h=600&fit=crop&auto=format',
    ],
    shortDesc: '11kV/415V distribution transformer, ONAN cooling, IEC 60076 compliant',
    description: 'The Siemens SIDAC distribution transformer is engineered for reliable power distribution in industrial and utility applications. Hermetically sealed tank design eliminates oil maintenance requirements. Suitable for outdoor installation with full weatherproofing.',
    spec: 'IEC 60076 · 11kV/415V · ONAN',
    specs: [
      { label: 'Standard', value: 'IEC 60076' },
      { label: 'Primary Voltage', value: '11 kV' },
      { label: 'Secondary Voltage', value: '415 V' },
      { label: 'Rated Power', value: '1,000 kVA' },
      { label: 'Cooling Type', value: 'ONAN' },
      { label: 'Frequency', value: '50 Hz' },
      { label: 'Vector Group', value: 'Dyn11' },
      { label: 'IP Rating', value: 'IP44' },
      { label: 'Installation', value: 'Outdoor' },
      { label: 'Weight', value: '2,850 kg' },
    ],
    applications: ['Power distribution substations', 'Factory power supply', 'Industrial parks', 'Construction sites'],
    tags: ['transformer', 'hv', 'distribution', 'power'],
    featured: true,
    certifications: ['IEC 60076', 'CE', 'ISO 9001'],
  },
  {
    id: 2,
    name: 'Industrial Air Compressor',
    sku: 'IM-CMP-002',
    brand: 'Parker',
    category: 'Industrial Machinery',
    subcategory: 'Compressors',
    model: 'PSCVSD-75',
    price: 14200,
    priceDisplay: '$14,200',
    priceUnit: 'per unit',
    moq: 1,
    leadTime: '4–6 weeks',
    stock: 5,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1717386255773-a456c611dc4e?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1717386255773-a456c611dc4e?w=800&h=600&fit=crop&auto=format'],
    shortDesc: 'Rotary screw, 75 kW, 10 bar operating pressure, variable speed drive',
    description: 'Energy-efficient variable-speed drive rotary screw air compressor. Integrated air drying and oil filtration. Smart controller with remote monitoring capability. Suitable for continuous duty industrial applications.',
    spec: 'Rotary Screw · 75 kW · 10 bar',
    specs: [
      { label: 'Type', value: 'Rotary Screw VSD' },
      { label: 'Motor Power', value: '75 kW' },
      { label: 'Working Pressure', value: '7 – 10 bar' },
      { label: 'Flow Rate', value: '10.8 m³/min' },
      { label: 'Noise Level', value: '68 dB(A)' },
      { label: 'Voltage', value: '400V / 3Ph / 50Hz' },
      { label: 'Tank Capacity', value: '500 L' },
      { label: 'Weight', value: '680 kg' },
    ],
    applications: ['Manufacturing plants', 'Automotive workshops', 'Pneumatic tools', 'Spray painting'],
    tags: ['compressor', 'air', 'pneumatic', 'vsd'],
    featured: true,
    certifications: ['CE', 'ISO 9001'],
  },
  {
    id: 3,
    name: 'Low Voltage MCC Panel',
    sku: 'EE-MCC-003',
    brand: 'ABB',
    category: 'Electrical Equipment',
    subcategory: 'Control Panels',
    model: 'ABB MNS 3.0',
    price: 9800,
    priceDisplay: '$9,800',
    priceUnit: 'per unit',
    moq: 1,
    leadTime: '6–8 weeks',
    stock: 8,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1635335874521-7987db781153?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1635335874521-7987db781153?w=800&h=600&fit=crop&auto=format'],
    shortDesc: 'Motor control center, IP54 protection, modular design, 400V system',
    description: 'ABB MNS modular low-voltage switchgear and motor control center. Form 4 separation for maximum safety. Withdrawable functional units for easy maintenance without system shutdown. Integrated PLC and SCADA interface options.',
    spec: 'IP54 · 400V · Modular Design',
    specs: [
      { label: 'Standard', value: 'IEC 61439-2' },
      { label: 'Rated Voltage', value: '690 V' },
      { label: 'System Voltage', value: '400 V / 50 Hz' },
      { label: 'Rated Current', value: 'Up to 6,300 A' },
      { label: 'Protection Degree', value: 'IP54' },
      { label: 'Form of Separation', value: 'Form 4B' },
      { label: 'Busbar Material', value: 'Copper' },
    ],
    applications: ['Motor control', 'Power distribution', 'Factory automation', 'Process control'],
    tags: ['mcc', 'switchgear', 'control panel', 'lv'],
    featured: true,
    certifications: ['IEC 61439', 'CE', 'ISO 9001'],
  },
  {
    id: 4,
    name: 'Industrial Robot Arm',
    sku: 'IM-ROB-004',
    brand: 'Mitsubishi Electric',
    category: 'Industrial Machinery',
    subcategory: 'Automation',
    model: 'RV-8CRL',
    price: 32000,
    priceDisplay: '$32,000',
    priceUnit: 'per unit',
    moq: 1,
    leadTime: '12–16 weeks',
    stock: 2,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1716191299980-a6e8827ba10b?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1716191299980-a6e8827ba10b?w=800&h=600&fit=crop&auto=format'],
    shortDesc: '6-axis articulated robot, 80 kg payload, ±0.05 mm repeatability',
    description: 'Mitsubishi Electric 6-axis industrial robot for welding, assembly, and material handling. Real-time collision detection. Compatible with MELFA BASIC VI programming language and visual sensor systems.',
    spec: '6-Axis · 80 kg · ±0.05 mm',
    specs: [
      { label: 'Type', value: '6-Axis Articulated' },
      { label: 'Payload', value: '80 kg' },
      { label: 'Reach', value: '2,050 mm' },
      { label: 'Repeatability', value: '±0.05 mm' },
      { label: 'Mounting', value: 'Floor / Ceiling' },
      { label: 'Drive', value: 'AC Servo' },
      { label: 'Weight', value: '535 kg' },
      { label: 'IP Rating', value: 'IP65 (Wrist)' },
    ],
    applications: ['Welding', 'Assembly', 'Material handling', 'Painting', 'Palletizing'],
    tags: ['robot', 'automation', '6-axis', 'welding'],
    featured: true,
    certifications: ['CE', 'ISO 10218'],
  },
  {
    id: 5,
    name: 'PPE Safety Helmet Set',
    sku: 'SF-PPE-005',
    brand: '3M',
    category: 'Safety & Fire Protection',
    subcategory: 'Personal Protective Equipment',
    model: '3M H-700 Series',
    price: 45,
    priceDisplay: '$45',
    priceUnit: 'per unit',
    moq: 10,
    stock: 500,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1567954970774-58d6aa6c50dc?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1567954970774-58d6aa6c50dc?w=800&h=600&fit=crop&auto=format'],
    shortDesc: 'ANSI Z89.1 certified, ABS shell, full brim, Class E rated, UV resistant',
    description: '3M H-700 Series hard hat with full brim design for maximum protection from falling objects, rain, and sun. 4-point suspension system for superior comfort. UV-stabilized ABS shell with 5-year replacement recommendation.',
    spec: 'ANSI Z89.1 · ABS Shell · Class E',
    specs: [
      { label: 'Standard', value: 'ANSI/ISEA Z89.1-2014' },
      { label: 'Class', value: 'Class E (Electrical)' },
      { label: 'Shell Material', value: 'ABS Plastic' },
      { label: 'Suspension', value: '4-Point Ratchet' },
      { label: 'Brim Type', value: 'Full Brim' },
      { label: 'Colors Available', value: 'White, Yellow, Orange, Blue' },
      { label: 'Weight', value: '380 g' },
      { label: 'Service Life', value: '5 Years' },
    ],
    applications: ['Construction sites', 'Manufacturing plants', 'Mining', 'Power plants', 'Utilities'],
    tags: ['ppe', 'helmet', 'safety', 'hardhat'],
    featured: true,
    certifications: ['ANSI Z89.1', 'EN 397'],
  },
  {
    id: 6,
    name: 'Heavy-Duty Power Cable',
    sku: 'CA-PWR-006',
    brand: 'Legrand',
    category: 'Cables & Accessories',
    subcategory: 'Power Cables',
    model: 'XLPE/SWA/PVC 11kV',
    price: 185,
    priceDisplay: '$185',
    priceUnit: 'per metre',
    moq: 50,
    stock: 2000,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1518181835702-6eef8b4b2113?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1518181835702-6eef8b4b2113?w=800&h=600&fit=crop&auto=format'],
    shortDesc: '3-core XLPE/SWA/PVC, 185 mm², 11kV rated, IEC 60502-2 compliant',
    description: 'Three-core armoured power cable for underground and direct burial installations. XLPE insulation provides excellent thermal and electrical properties. Steel wire armour provides mechanical protection. Suitable for industrial medium voltage distribution.',
    spec: 'IEC 60502-2 · 11kV · 185 mm²',
    specs: [
      { label: 'Standard', value: 'IEC 60502-2' },
      { label: 'Voltage Rating', value: '11 kV (12.7/11 kV)' },
      { label: 'Conductor Size', value: '185 mm²' },
      { label: 'Cores', value: '3' },
      { label: 'Conductor Material', value: 'Stranded Copper' },
      { label: 'Insulation', value: 'XLPE' },
      { label: 'Armour', value: 'Steel Wire Armour (SWA)' },
      { label: 'Outer Sheath', value: 'PVC' },
      { label: 'Operating Temp.', value: '90°C' },
      { label: 'Weight', value: '18.5 kg/m' },
    ],
    applications: ['Underground distribution', 'Power plant cabling', 'Industrial facilities', 'Substations'],
    tags: ['cable', 'power', 'xlpe', 'armoured', 'mv'],
    featured: true,
    certifications: ['IEC 60502-2', 'BS 7870'],
  },
  {
    id: 7,
    name: 'Digital Clamp Meter',
    sku: 'TE-CLM-007',
    brand: 'Fluke',
    category: 'Tools & Equipment',
    subcategory: 'Test & Measurement',
    model: 'Fluke 376 FC',
    price: 420,
    priceDisplay: '$420',
    priceUnit: 'per unit',
    moq: 1,
    stock: 50,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1758101755915-462eddc23f57?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1758101755915-462eddc23f57?w=800&h=600&fit=crop&auto=format'],
    shortDesc: 'True-RMS, 1000A AC/DC, Fluke Connect wireless, CAT IV 600V rated',
    description: 'Fluke 376 FC True-RMS AC/DC clamp meter with iFlex flexible current probe. Fluke Connect wireless capability for remote monitoring. CAT IV 600V / CAT III 1000V safety rating for use in demanding environments.',
    spec: 'True-RMS · 1000A · CAT IV 600V',
    specs: [
      { label: 'AC Current', value: '1,000 A' },
      { label: 'DC Current', value: '1,400 A (with iFlex)' },
      { label: 'AC Voltage', value: '1,000 V' },
      { label: 'DC Voltage', value: '1,000 V' },
      { label: 'Measurement', value: 'True-RMS' },
      { label: 'Safety Rating', value: 'CAT IV 600V / CAT III 1000V' },
      { label: 'Connectivity', value: 'Fluke Connect Wireless' },
      { label: 'Display', value: '6,000 Count LCD' },
    ],
    applications: ['Electrical testing', 'Maintenance', 'Troubleshooting', 'Power quality'],
    tags: ['clamp meter', 'testing', 'electrical', 'measurement'],
    featured: false,
    certifications: ['CE', 'CAT IV', 'UL'],
  },
  {
    id: 8,
    name: 'Circuit Breaker — Molded Case',
    sku: 'EE-MCB-008',
    brand: 'Schneider Electric',
    category: 'Electrical Equipment',
    subcategory: 'Circuit Breakers',
    model: 'EasyPact EZC400',
    price: 680,
    priceDisplay: '$680',
    priceUnit: 'per unit',
    moq: 1,
    stock: 120,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?w=800&h=600&fit=crop&auto=format'],
    shortDesc: '400A, 36kA breaking capacity, 3-pole, IEC 60947-2 compliant',
    description: 'Schneider Electric EasyPact EZC molded case circuit breaker for industrial and commercial applications. Compact design with high breaking capacity. Adjustable thermal and magnetic trip settings.',
    spec: 'IEC 60947-2 · 400A · 36kA',
    specs: [
      { label: 'Standard', value: 'IEC 60947-2' },
      { label: 'Rated Current', value: '400 A' },
      { label: 'Breaking Capacity', value: '36 kA' },
      { label: 'Poles', value: '3' },
      { label: 'Voltage', value: '415 V AC' },
      { label: 'Frequency', value: '50/60 Hz' },
      { label: 'Trip Unit', value: 'Thermal-Magnetic' },
    ],
    applications: ['Motor protection', 'Feeder protection', 'Panel boards', 'Distribution boards'],
    tags: ['circuit breaker', 'mccb', 'protection', 'switchgear'],
    featured: false,
    certifications: ['IEC 60947-2', 'CE'],
  },
  {
    id: 9,
    name: 'Industrial Rotary Pump',
    sku: 'IM-PMP-009',
    brand: 'Parker',
    category: 'Industrial Machinery',
    subcategory: 'Pumps',
    model: 'Parker PGM620',
    price: 3800,
    priceDisplay: '$3,800',
    priceUnit: 'per unit',
    moq: 1,
    leadTime: '3–4 weeks',
    stock: 12,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1717386255767-52643970d483?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1717386255767-52643970d483?w=800&h=600&fit=crop&auto=format'],
    shortDesc: 'Gear pump, 620 cc/rev, high pressure hydraulic, 350 bar max',
    description: 'Parker PGM620 high-pressure gear pump for demanding hydraulic applications. Excellent volumetric efficiency and long service life. Available in multiple displacement options and shaft configurations.',
    spec: 'Gear Pump · 620 cc/rev · 350 bar',
    specs: [
      { label: 'Type', value: 'External Gear Pump' },
      { label: 'Displacement', value: '620 cc/rev' },
      { label: 'Max Pressure', value: '350 bar' },
      { label: 'Max Speed', value: '1,800 RPM' },
      { label: 'Fluid', value: 'Mineral Oil' },
      { label: 'Mounting', value: 'SAE A/B Flange' },
      { label: 'Port Size', value: '1-1/4" BSP' },
    ],
    applications: ['Hydraulic systems', 'Press machines', 'Mobile machinery', 'Industrial automation'],
    tags: ['pump', 'hydraulic', 'gear pump', 'fluid power'],
    featured: false,
    certifications: ['CE', 'ISO 4413'],
  },
  {
    id: 10,
    name: 'Fire Suppression System',
    sku: 'SF-FIR-010',
    brand: 'Honeywell',
    category: 'Safety & Fire Protection',
    subcategory: 'Fire Suppression',
    model: 'Gent S4-34000',
    price: 12500,
    priceDisplay: '$12,500',
    priceUnit: 'per unit',
    moq: 1,
    leadTime: '6–10 weeks',
    stock: 4,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1662309376159-b95fb193d96b?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1662309376159-b95fb193d96b?w=800&h=600&fit=crop&auto=format'],
    shortDesc: 'Addressable fire alarm & suppression panel, 4-loop, 128 devices per loop',
    description: 'Honeywell Gent S4 intelligent fire alarm control panel for large-scale industrial and commercial facilities. Addressable loop technology for precise location identification. Integrated suppression control for gas and water systems.',
    spec: '4-Loop · 512 Devices · Addressable',
    specs: [
      { label: 'Type', value: 'Addressable Fire Panel' },
      { label: 'Loops', value: '4' },
      { label: 'Devices/Loop', value: '128' },
      { label: 'Total Devices', value: '512' },
      { label: 'Supply Voltage', value: '230V AC' },
      { label: 'Battery Backup', value: '24h standby' },
      { label: 'Communication', value: 'BACnet/IP, RS-485' },
      { label: 'Standards', value: 'EN 54, UL864' },
    ],
    applications: ['Industrial facilities', 'Data centers', 'Warehouses', 'Power plants'],
    tags: ['fire', 'suppression', 'alarm', 'safety system'],
    featured: false,
    certifications: ['EN 54', 'UL 864', 'CE'],
  },
  {
    id: 11,
    name: 'Rotary Screw Generator Set',
    sku: 'PE-GEN-011',
    brand: 'Eaton',
    category: 'Power & Energy',
    subcategory: 'Generators',
    model: 'Eaton PW9355',
    price: 68000,
    priceDisplay: '$68,000',
    priceUnit: 'per unit',
    moq: 1,
    leadTime: '10–14 weeks',
    stock: 1,
    stockLabel: 'Low Stock',
    img: 'https://images.unsplash.com/photo-1513257805917-a0da1146eb15?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1513257805917-a0da1146eb15?w=800&h=600&fit=crop&auto=format'],
    shortDesc: '500 kVA standby generator, diesel, 415V / 3-phase, soundproofed canopy',
    description: 'Eaton 500 kVA standby diesel generator with acoustic canopy for noise reduction. Automatic transfer switch included. AMF control panel with remote monitoring. Suitable for data centers, hospitals, and critical facilities.',
    spec: '500 kVA · Diesel · 415V 3-Phase',
    specs: [
      { label: 'Standby Rating', value: '500 kVA / 400 kW' },
      { label: 'Prime Rating', value: '450 kVA / 360 kW' },
      { label: 'Engine', value: '6-Cylinder Turbocharged Diesel' },
      { label: 'Voltage', value: '415V / 3Ph / 50Hz' },
      { label: 'Fuel Consumption', value: '108 L/h at full load' },
      { label: 'Noise Level', value: '75 dB(A) at 7m' },
      { label: 'Tank Capacity', value: '1,000 L' },
      { label: 'Weight', value: '4,800 kg' },
    ],
    applications: ['Critical power backup', 'Data centers', 'Hospitals', 'Industrial facilities', 'Power plants'],
    tags: ['generator', 'genset', 'diesel', 'standby power'],
    featured: false,
    certifications: ['CE', 'ISO 8528', 'BS 7698'],
  },
  {
    id: 12,
    name: 'Diamond Core Drill',
    sku: 'TE-DRL-012',
    brand: 'Hilti',
    category: 'Tools & Equipment',
    subcategory: 'Drilling Equipment',
    model: 'Hilti DD 500-CA',
    price: 3200,
    priceDisplay: '$3,200',
    priceUnit: 'per unit',
    moq: 1,
    stock: 15,
    stockLabel: 'In Stock',
    img: 'https://images.unsplash.com/photo-1524514587686-e2909d726e9b?w=600&h=400&fit=crop&auto=format',
    images: ['https://images.unsplash.com/photo-1524514587686-e2909d726e9b?w=800&h=600&fit=crop&auto=format'],
    shortDesc: 'Diamond core drill, 5 kW, up to 500mm core diameter, automatic water supply',
    description: 'Hilti DD 500-CA high-performance diamond core drill for concrete, reinforced concrete, and masonry. Automatic water supply system and integrated dust extraction. Suitable for HVAC openings, electrical conduit installations.',
    spec: '5 kW Motor · 500mm Core · Auto-Water',
    specs: [
      { label: 'Motor Power', value: '5 kW' },
      { label: 'Max Core Diameter', value: '500 mm' },
      { label: 'Voltage', value: '230V / 50Hz' },
      { label: 'Drilling Speed', value: '0 – 980 RPM' },
      { label: 'Water Flow', value: 'Automatic' },
      { label: 'Weight', value: '21 kg' },
      { label: 'Drilling Depth', value: 'Up to 790 mm' },
    ],
    applications: ['Concrete drilling', 'HVAC openings', 'Electrical conduits', 'Construction'],
    tags: ['drill', 'diamond core', 'concrete', 'construction'],
    featured: false,
    certifications: ['CE', 'EN 60745'],
  },
]

export const ORDERS = [
  {
    id: 'NB-2024-0045',
    date: '2024-11-15',
    status: 'Delivered',
    statusColor: '#16a34a',
    items: [
      { name: 'High-Voltage Power Transformer', qty: 1, price: 28500, sku: 'EE-TRF-001' },
      { name: 'Heavy-Duty Power Cable', qty: 100, price: 18500, sku: 'CA-PWR-006' },
    ],
    total: 47000,
    deliveryDate: '2024-11-28',
  },
  {
    id: 'NB-2024-0031',
    date: '2024-10-03',
    status: 'Processing',
    statusColor: '#0099FF',
    items: [
      { name: 'Low Voltage MCC Panel', qty: 2, price: 19600, sku: 'EE-MCC-003' },
    ],
    total: 19600,
    deliveryDate: '2024-10-20',
  },
  {
    id: 'NB-2024-0019',
    date: '2024-08-22',
    status: 'Delivered',
    statusColor: '#16a34a',
    items: [
      { name: 'PPE Safety Helmet Set', qty: 50, price: 2250, sku: 'SF-PPE-005' },
      { name: 'Digital Clamp Meter', qty: 5, price: 2100, sku: 'TE-CLM-007' },
    ],
    total: 4350,
    deliveryDate: '2024-09-01',
  },
]

export const QUOTATIONS = [
  {
    id: 'Q-2024-0018',
    date: '2024-11-10',
    validUntil: '2024-12-10',
    status: 'Quoted',
    statusColor: '#7c3aed',
    items: [
      { name: 'Rotary Screw Generator Set', qty: 2, unitPrice: 68000, total: 136000, sku: 'PE-GEN-011' },
    ],
    total: 136000,
  },
  {
    id: 'Q-2024-0011',
    date: '2024-09-18',
    validUntil: '2024-10-18',
    status: 'Accepted',
    statusColor: '#16a34a',
    items: [
      { name: 'Industrial Robot Arm', qty: 3, unitPrice: 32000, total: 96000, sku: 'IM-ROB-004' },
    ],
    total: 96000,
  },
  {
    id: 'Q-2024-0005',
    date: '2024-07-30',
    validUntil: '2024-08-30',
    status: 'Expired',
    statusColor: '#94a3b8',
    items: [
      { name: 'Fire Suppression System', qty: 1, unitPrice: 12500, total: 12500, sku: 'SF-FIR-010' },
    ],
    total: 12500,
  },
]
